config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  unauthenticated do
    as :user do
      root :to => 'devise/registrations#new'
    end
  end
  root "users#show"
  resources :users, only: [:show] 
  controller :tangos do
    resources :tangos, only: [:create, :destroy] do
      collection do
        get 'drillnew', to: "tangos#drillnew"
        get 'drilltest', to: "tangos#drilltest"
        post 'drillmark', to: "tangos#drillmark"
      end
    end
    scope path: 'flush' do
      get 'flush_tangos', action: :show
    end
  end
  resources :tests, only: [:index] do
    collection do
      get 'test', to: "tests#test"
      post 'mark', to: "tests#mark"
    end
  end
end

app/views/shared/_bodyMainHead.html.haml
.body__main__head
  .body__main__head__function
    = link_to "ドリル", drillnew_tangos_path(current_user)
  .body__main__head__function
    - if @tangos.blank?
      %p1 フラッシュ
      %br
      %p2 （My単語を登録で利用できます）
    - else
      = link_to "フラッシュ", flush_tangos_path(current_user)
  .body__main__head__function
    - if @tangos.blank?
      %p1 テスト
      %br
      %p2 (My単語を登録で利用できます)
    - else
      = link_to "テスト", test_tests_path(current_user)
  .body__main__head__function
    = link_to "マイページ", user_path(current_user)

app/views/shared/_header.html.haml
.header
  %h.header__title
    MY単語
  .header__right
    - if user_signed_in?
      .header__right__link
        =link_to "ログアウト", destroy_user_session_path, method: :delete 
    - else
      .header__right__link
        = link_to "ログイン", new_session_path(resource_name)