config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  unauthenticated do
    as :user do
      root :to => 'devise/registrations#new'
    end
  end
  root "users#show"
  resources :users, only: [:show] 
  controller :tangos do
    resources :tangos, only: [:create, :destroy] do
      collection do
        get 'drillnew', to: "tangos#drillnew"
        get 'drilltest', to: "tangos#drilltest"
        post 'drillmark', to: "tangos#drillmark"
      end
    end
    scope path: 'flush' do
      get 'flush_tangos', action: :show
    end
  end
  resources :tests, only: [:index] do
    collection do
      get 'test', to: "tests#test"
      post 'mark', to: "tests#mark"
    end
  end
end

app/models/tango.rb
class Tango < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  attr_accessor :left_question, :right_anser
  belongs_to_active_hash :drill1
  
  belongs_to :user

  scope :recent, -> { order(created_at: :desc)}
  
  def anser?(reply)
    return self.anser == reply
  end

  # def correct?(reply)
  #   return self.anser == reply
  # end
  validates :anser, presence: true, format: {with: /\A[a-z0-9]+\z/, message: 'は半角アルファベットで入力してください'}
  validates :question, presence: true
end

app/controllers/tangos_controller.rb
class TangosController < ApplicationController

  def create
    @tangos = Tango.create(tango_params)
    redirect_to "/"
  end

  def destroy
    tango = Tango.find(params[:id])
    tango.destroy
    redirect_to "/"
  end
  
  def show
    @tangos = Tango.where(user_id: current_user.id).sample(5)
  end

  def drillnew
    @tangos = Tango.where(user_id: current_user.id)
  end

  def drill1test
    @quizzes = Drill1.all
    @tangos = Tango.where(user_id: current_user.id)
  end

  def drillmark
    @tangos = Tango.where(user_id: current_user.id)
    quizzes = Drill1.find(params[:quiz])
    @ansers = []
    quizzes.each do |q|
      @ansers << {quiz: q, right: q.anser?(params["quiz#{q.id}"])}
    end
  end

  
  private
  def tango_params
    params.require(:tango).permit(:question, :anser, :result).merge(user_id: current_user.id)
  end
end

app/helpers/tangos_helper.rb
module TangosHelper
end

app/views/tangos/drillmark.html.haml
.body
  .body__main
    = render "shared/bodyMainHead"
    .body__main__contents
      .body__main__contents__index
        わからなかった単語はお気に入り登録しよう！
        %br  
        %br  
        -@ansers.each do |anser|
          .body__main__contents__index__problems
            .body__main__contents__index__problems__japanese
              =anser[:quiz].question
            .body__main__contents__index__problems__english
              =anser[:quiz].anser
            .body__main__contents__index__problems__result
              =anser[:right] ? " 💮" : "×"
    .body__main__hide
      -@tangos.each do |anser|
        =anser.question

app/views/tangos/drillnew.html.haml
.body
  .body__main
    = render "shared/bodyMainHead"
    .body__main__contents
      ドリルにチャレンジして新しい単語を覚えよう！
      .body__main__contents__drill
        = link_to "ドリル１", drilltest_tangos_path(current_user)
      .body__main__contents__drill
        ドリル２
        %p5 (未実装)
      .body__main__contents__drill
        ドリル３
        %p5 (未実装)
      .body__main__contents__drill
        ドリル４
        %p5 (未実装)
      .body__main__contents__drill
        ドリル５
        %p5 (未実装)
    .body__main__hide
      -@tangos.each do |anser|
        =anser.question

app/views/tangos/drilltest.html.haml
.body
  .body__main
    = render "shared/bodyMainHead"
    .body__main__contents
      .body__main__contents__index
        %h 単語ドリル レベル１ 50問の英単語にチャレンジ！
        %br  
        %br  
      =form_tag drillmark_tangos_path do
        -@quizzes.each do |quiz|
          .body__main__contents__index__problems
            .body__main__contents__index__problems__japanese
              =quiz.question
            .body__main__contents__index__problems__english
              =hidden_field_tag  "quiz[]", quiz.id
              =text_field_tag "quiz#{quiz.id}","",autocomplete: 'off', placeholder: "英単語", size: "20x20", class: "body__main__contents__register__problems__english__einput"
        =submit_tag "回答", class: "btn"
    .body__main__hide
      -@tangos.each do |anser|
        =anser.question

app/views/tangos/show.html.haml
.body
  .body__main
    = render "shared/bodyMainHead"
    .body__main__contents
      .body__main__contents__index
        登録した単語をフラッシュで覚えよう！
        %br
        #timer 5
        -@tangos.each do |tango|
          .body__main__contents__index__problems
            .body__main__contents__index__problems__japanese
              =tango.question
            .body__main__contents__index__problems__english
              =tango.anser